### ISSUE TITLE
Compressed input

### ISSUE THREAD

**Issue by cookie-1921** [D3lt4lph4/jpeg_deep#5]
hi，thanks for your sharing~
Could you tell me how the compressed input is prepared.

**Comment by D3lt4lph4** [comment]
Hi,

First data-augmentation is carried in the RGB domain, then the augmented image is compressed back into a jpeg image and finally un-compressed up to the DCT representation.

The data-augmentation used for the SSD like network is the one described in the original paper, as for the classification task I simply did resizing (smallest side to 256), crop (224x224) and flip (with probability of 0.5).

Hope this answer your question.

**Comment by cookie-1921** [comment]
Your reply really help me a lot.  I got the answer where to output DCT presentation. Also thank you very much for telling me about the image augmentation.
